### PR TITLE
Upgrade the octopus deploy cookbook to use custom resources

### PR DESCRIPTION
**Pull request by bigbam505**
This is the first step in moving the new octopus deploy server to a stable release.  I have moved the install recipes into a LWRP and added install / remove methods so you can install or remove octopus deploy server / tentacle.

### CODE REVIEW

**Comment by bigbam505** [comment]
@jonathanmorley wanna take a took?

**Comment by jonathanmorley** [comment]
Looks good, only thing im a little confused by is that you seem to have removed the configure recipes. Is there a replacement for them that I missed?

**Comment by bigbam505** [comment]
It is missing ATM plan on adding it in another PR later.  Just wanted to get the installation converted into a resource. The new resource will also only support 3.0 + just for simplicity.

**Comment by bigbam505** [comment]
Just haven't implemented them yet.

--
Sent from a rotary phone.

On Sep 24, 2015 11:00 PM, Jonathan Morley <notifications@github.com> wrote:
>
> Looks good, only thing im a little confused by is that you seem to have removed the conf

Looks good, only thing im a little confused by is that you seem to have removed the configure recipes. Is there a replacement for them that I missed?

**Pull request merged**
