### PR TITLE
Fix issue #134

### PR DESCRIPTION
**Pull request by spuder**
Should fix issue #134 (not tested)

I decided to use symbols since they should never change. Perhaps strings would be better. 

This converts the symbols to strings before the map `new_resource.tenated_deployment_participation.to_s`

I'm still not sure why the appveyor tests aren't catching this.

### CODE REVIEW

**Comment by brentm5** [comment]
I feel that we should maybe create a new method to correct this.  Its because the other ones pass in a list where as this one only is one.  You can correct it by making that a symbol array such as 

```
#{option('tenanted-deployment-participation', new_resource.tenated_deployment_participation)}
```

```
def option(name, option)
  option_list(name, [option]) if name && option
end
```

**Comment by brentm5** [comment]
I am going to fix it like above, don't want this to break someone overnight or something

**Comment by spuder** [comment]
Sounds good to me.

**Comment by brentm5** [comment]
Thanks for reporting!

**Comment by spuder** [comment]
The other options could proabably be refactored to use the new 'option' method

--instance "#{new_resource.instance}"  
--server "#{new_resource.server}"   
--name "#{new_resource.tentacle_name}"   
--publicHostName "#{new_resource.public_dns}"   
--apiKey "#{new_resource.api_key}"

**Comment by brentm5** [comment]
Yup, I was planning to revist that when I enable version 4.0 to work.

**Pull request closed without merging**
